# Generated by Django 4.1.1 on 2023-03-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_caloeachday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloeachday',
            name='date_time_save',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
