# Generated by Django 4.1.1 on 2023-03-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_caloeachday_date_time_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaloEachDay',
        ),
    ]
