# Generated by Django 4.1.1 on 2023-03-19 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=300)),
                ('postcontent', models.TextField(null=True)),
                ('topictype', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('date_post', models.DateTimeField(auto_now_add=True, null=True)),
                ('picture', models.ImageField(upload_to='blog_pictures')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
