# Generated by Django 4.1.1 on 2023-03-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitecontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='contact',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
