# Generated by Django 4.1.1 on 2023-02-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameoffood',
            name='name_food',
            field=models.TextField(),
        ),
    ]
