# Generated by Django 4.1.1 on 2023-02-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_nameoffood_name_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameoffood',
            name='name_food',
            field=models.CharField(max_length=100),
        ),
    ]
