# Generated by Django 4.1.1 on 2023-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_nameoffood_name_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exertion_intensity', models.CharField(max_length=100)),
                ('ARM_factor', models.IntegerField()),
            ],
        ),
    ]
