# Generated by Django 4.1.1 on 2023-03-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_arm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm',
            name='ARM_factor',
            field=models.FloatField(),
        ),
    ]
