# Generated by Django 4.1.1 on 2023-03-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_arm_arm_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm',
            name='exertion_intensity',
            field=models.CharField(choices=[('Ít vận động( ít hoặc không tập thể dục)', 'Ít vận động( ít hoặc không tập thể dục)'), ('Vận động cường độ cao', 'Vận động cường độ cao'), ('Vận động nhẹ( tập thể dục 1-3 ngày/tuần)', 'Vận động nhẹ( tập thể dục 1-3 ngày/tuần)'), ('Vận động vừa phải( Tập thể dục 3-5 ngày/tuần)', 'Vận động vừa phải( Tập thể dục 3-5 ngày/tuần)'), ('Vận động nhiều( tập thể dục 6-7 ngày/tuần)', 'Vận động nhiều( tập thể dục 6-7 ngày/tuần)')], max_length=100, null=True),
        ),
    ]
